title: Lisya Apriliani
logo: /images/profile-lisya.png?raw=true
description: >-
  <p align="center"> <a href="https://www.linkedin.com/in/lisya-apriliani/">
  LinkedIn </a> </p> <br> <p align="justify">A Computer Science graduate who is
  always willing to work hard. Bringing forth a motivated attitude and a variety
  of powerful skills. Has a great interest in the field of organization,
  analysis, data processing, and application development.</p> <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0
